CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION lia_admin;

CREATE TABLE core.pca (
    item INT,
    unidade_requisitante TEXT,
    orcamento_ordinario_ou_pleitos TEXT,
    programa_unidade_responsavel TEXT,
    quantidade_a_ser_adquirida INT,
    valor_estimado TEXT,
    objeto_contratacao TEXT,
    codigo_catalogo_catmat_catser TEXT,
    justificativa_aquisicao TEXT,
    potencialmente_compartilhavel TEXT,
    vcto_contrato_em_vigor TEXT,
    data_maxima_prorrogacao_contrato TEXT,
    iniciar_providencias_contratacao TEXT,
    data_estimada_contratacao TEXT,
    prioridade TEXT,
    objetivo_estrategico_vinculado TEXT,
    processo_sei TEXT,
    evento_solicitacao TEXT,
    anotacoes TEXT
);

INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (1,'EJE/STI/SEDES','Ordinário e Pleitos','CUSTEIO33903948EJE/STI/SEDES',NULL,'335000,00','CAPACITAÇÃO','','Cursos de formação continuada visando a atualização, desenvolvimento e aprimoramento de competências de Juízes, Servidores e Colaboradores da Justiça Eleitoral que atuarão nas questões jurídicas afetas ao processo eleitoral.','Não','','','01/12/25','01/06/26','Alta','Garantia dos direitos fundamentais Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitoraisFortalecimento da relação institucional com a sociedade Agilidade e produtividade na prestação jurisdicional','','756158 e 754530',''),
	 (2,'SEGLOF','Ordinário','CUSTEIO33903901SEGLOF',5,'16000,00','PLATAFORMA ZÊNITE FÁCIL','61223108','A presente contratação é valiosa ferramenta de consulta e de pesquisa na doutrina, na legislação e na jurisprudência dos Tribunais Judiciais (STF, STJ, TST, TRFs, TJs etc.), bem como das Cortes de Contas (TCU e TCEs). Incorpora, também, a essa contratação a resposta mediante parecer, por escrito, em um máximo de cinco consultas por ano, sobre licitações e contratos administrativos, encaminhadas à Zênite Informação e Consultoria S.A. Essas ferramentas dão suporte aos vários órgãos que compõem este tribunal, na área de Licitações e Contratos, proporcionando subsídios para o planejamento das contratações, para a instrução dos processos administrativos e para as constantes decisões tomadas pela Presidência, Assessoria Jurídica da DiretoriaGeral, Assessoria de Editais e Contratos, objetivando atender ao que preceitua a Lei Maior no seu art.37,XXI, regulamentado pela Lei n.º 8.666/1993 (atualmente revogado, mas que permanece regendo as contratações celebradas sob sua égide) e pela Lei 14.133/2021.','Sim','','','07/01/26','01/06/26','Média','Aperfeiçoamento da gestão orçamentária e financeira','','751550',''),
	 (3,'ASPLAN','Ordinário','CUSTEIO33903941ASPLAN ',NULL,'154497,00',' FORNECIMENTO DE COFEEBREAK ','63212807','Disponibilizar de coffeebreak em eventos realizados pelo Tribunal','Não','12/06/26','12/06/2027','12/02/2026','12/06/2026','Baixa','Agilidade e produtividade na prestação jurisdicional/Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais','000027192.2024.6.01.8000','','Contratado'),
	 (4,'CERIMONIAL','Ordinário','CUSTEIO33903923CERIMONIAL ',NULL,'30000,00','DECORAÇÃO DE AMBIENTES COM FLORES E BUQUES','96917019','Festividades a serem realizadas por este Regional','Não','','','','07/01/2026','Média','Aperfeiçoamento da gestão administrativa e da governança judiciária','000038446.2024.6.01.8000','',''),
	 (5,'SRJAR','Ordinário','CUSTEIO33903635SRJAR',NULL,'7800,00','CONSERTO DAS VESTES TALARES','','Manter as vestes talares em perfeitas condições de usabilidade pelos membros da Corte, secretário(a) judiciário(a) e advogados(as), durante a realização das Sessões Plenárias. ','Não','','','01/06/2025','07/01/2026','Baixa','Promoção da sustentabilidade','000188654.2023.6.01.8000','',''),
	 (6,'SGEC','Ordinário','CUSTEIO33903905SGEC',NULL,'76452,00','INTÉRPRETE DE LIBRAS','83912637',' Facilitar a comunicação, garantindo o acesso à informação para a pessoa surda que se comunica por meio da Língua Brasileira de Sinais','Não','15/01/26','15/01/2035','01/09/2025','15/01/2026','Alta','Fortalecimento da relação institucional com a sociedade','000052417.2023.6.01.8000','',''),
	 (7,'GAJUD','Ordinário e Pleitos','CUSTEIO33903979GAJUD ',440,'78925,00',' OPERADOR DE SOM','85913749','Operação técnica especializada nos equipamentos de áudio e vídeo durante as Sessões Plenárias','Não','13/01/27','13/01/2028','13/10/2026','13/01/2027','Alta','Fortalecimento da relação institucional com a sociedade/Aperfeiçoamento da gestão administrativa e da governança judiciária','000133540.2024.6.01.8000','',''),
	 (8,'SASBEN','Ordinário','CUSTEIO 33903979  SASBEN',12,'4800,00','COLETA DE LIXO HOSPITALAR (LIXO ODONTOLÓGICO)','94219380','A contratação de empresa especializada na coleta de lixo hospitalar visa evitar a proliferação de microorganismos nocivos à saúde humana, bem como evitar o risco de contaminação ambiental. A contratação do serviço indicado no Item 2 também objetiva dar a destinação adequada ao lixo hospitalar, uma vez que não se pode descartálo sem o devido tratamento. Considerando que o TREAC não conta com esse tipo de serviço, fazse necessária a contratação de empresa especializada com qualificação para tanto. 
Considerando a necessidade de cumprimento das normas de sustentabilidade, de proteção e preservação do meioambiente, tornase indispensável a contratação pretendida.','Não','','','','07/01/2026','Alta','Promoção da sustentabilidade Melhoria da gestão de pessoas','000193646.2024.6.01.8000','757332',''),
	 (9,'SASBEN','Ordinário','CUSTEIO33903917SASBEN ',12,'14400,00',' MANUTENÇÃO PREVENTIVA E CORRETIVA DOS EQUIP. ODONTOLÓGICOS','8735797','Necessidade de manter os equipamentos em bom estado de conservação e pronto para serem utilizados','Não','18/11/25','18/11/2026','18/07/2026','18/11/2025','Alta','Promoção da sustentabilidade  Melhoria da gestão de pessoas','000076202.2024.6.01.8000','757229',''),
	 (10,'SASBEN','Ordinário','CUSTEIO 33903905  SASBEN',NULL,'118800,00','PSICOTERAPIA','93112572','Acompanhamento da saúde dos servidores','Não','','','','','Alta','Garantia dos direitos fundamentais Promoção da sustentabilidade Melhoria da gestão de pessoas','000176067.2024.6.01.8000','757357','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (11,'SASBEN','Ordinário','CUSTEIO 33903905  SASBEN',NULL,'31200,00','DESENVOLVIMENTO DE SAÚDE MENTAL','','Rodas de conversa, psicoterapia em grupo, palestras, mediação de conflito, prevenção de riscos psicossociais','Não','','','','','Alta','Garantia dos direitos fundamentais Promoção da sustentabilidade Melhoria da gestão de pessoas','','',''),
	 (12,'SEADE','Ordinário','CUSTEIO33903944SEADE ',NULL,'81000,00','SERVIÇO DE ÁGUA POTÁVEL ENCANADA E ESGOTO','69222845','A contratação do serviço de fornecimento de água encanada e esgotamento sanitário para os cartórios eleitorais e postos de atendimento ao eleitor (PAEs) na capital e no interior do Estado é fundamental para garantir a continuidade das atividades da Justiça Eleitoral, proporcionando condições adequadas de trabalho e atendimento ao público.','Não','','','','','Alta','Garantia dos direitos fundamentais','','0755738 e 0755706',''),
	 (13,'SEADE','Ordinário e Pleitos','CUSTEIO33903004SEADE',30,'5732,60',' GÁS DE COZINHA','461517','A aquisição de gás liquefeito de petróleo (GLP) em botijas de 13 kg para os prédios do Tribunal Regional Eleitoral do Acre (TREAC), na capital do Estado, é essencial para garantir o funcionamento adequado das atividades institucionais que demandam o uso desse insumo','Não','','30/08/2025','07/01/2026','14/05/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade Qualidade e Segurança no Ambiente Institucional','000160598.2023.6.01.8000','755728 e 0757922 e ',''),
	 (14,'SEADE','Ordinário','CUSTEIO33903007SEADE',200,'3947,36',' ÁGUA MINERAL','445485','Atendimento das necessidades humanas de consumo de água deste Tribunal na Capital','Não','','30/08/2025','07/01/2026','14/05/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade Qualidade e Segurança no Ambiente Institucional','000160598.2023.6.01.8001','755730 e 0757925',''),
	 (41,'SEDES','Ordinário','CUSTEIO33903925SEDES ',NULL,'20000,00',' SERVIÇO DE AGENTE DE INTEGRAÇÃO DE ESTÁGIO','92915156','Custeio do Programa de Estágio','Não','18/09/25','18/09/2028','18/06/2025','18/09/2025','Média','Fortalecimento da relação institucional com a sociedade','000053631.2023.6.01.8000','','Atentar ao prazo de prorrogação'),
	 (15,'SEADE','Ordinário','CUSTEIO33903007SEADE',20,'595,99','VASILHAMES PLÁSTICOS PARA ÁGUA MINERAL ','402921','A aquisição de vasilhames tipo galão de 20 litros para a troca e substituição de água mineral envasada é essencial para garantir o fornecimento contínuo e adequado de água potável nos prédios do Tribunal Regional Eleitoral do Acre (TREAC), na capital do Estado. Embora o Tribunal já possua um contrato de purificadores de água, a substituição regular dos galões é necessária para assegurar o abastecimento eficiente em todas as unidades','Não','','30/08/2025','07/01/2026','14/05/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade Qualidade e Segurança no Ambiente Institucional','000160598.2023.6.01.8002','755731',''),
	 (16,'SEADE','Ordinário e Pleitos','CUSTEIO33903044SEADE',NULL,'5803,75','FITA PARA CRACHÁ','83922810','A aquisição de crachás e fitas para crachás é essencial para garantir a identificação segura e eficiente de servidores e colaboradores nas dependências do Tribunal Regional Eleitoral do Acre (TREAC). Estes itens são fundamentais para o controle de acesso e a organização interna, assegurando que todos os envolvidos nas atividades diárias do Tribunal sejam facilmente identificados, promovendo um ambiente mais seguro e bem estruturado.','Não','','','01/07/25','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','000269777.2024.6.01.8000','755732','Em elaboração dos artefatos da contratação'),
	 (17,'SEADE','Ordinário e Pleitos','CUSTEIO33903044SEADE',NULL,'7418,65','CRACHÁ','88110111','A aquisição de crachás e fitas para crachás é essencial para garantir a identificação segura e eficiente de servidores e colaboradores nas dependências do Tribunal Regional Eleitoral do Acre (TREAC). Estes itens são fundamentais para o controle de acesso e a organização interna, assegurando que todos os envolvidos nas atividades diárias do Tribunal sejam facilmente identificados, promovendo um ambiente mais seguro e bem estruturado.','Não','','','01/07/25','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','000269777.2024.6.01.8001','755732','Em elaboração dos artefatos da contratação'),
	 (18,'SEADE','Ordinário e Pleitos','CUSTEIO  33903983  SEADE',NULL,'28716,21','IMPRESSÕES A4 E GRANDES FORMATOS, PRETO E BRANCO E COLORIDO','','Contratação de serviços de impressão em grandes formatos, plastificação, encadernação, carimbos e reprografia','Não','','','01/07/25','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','000269777.2024.6.01.8002','755732','Em elaboração dos artefatos da contratação'),
	 (18,'SEADE','Ordinário e Pleitos','CUSTEIO 33903983  SEADE',NULL,'19337,07','CÓPIA DE DOCUMENTOS EM PRETO E BRANCO E COLORIDO','','Contratação de serviços de impressão em grandes formatos, plastificação, encadernação, carimbos e reprografia','Não','','','01/07/25','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','000269777.2024.6.01.8003','755732','Em elaboração dos artefatos da contratação');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (18,'SEADE','Ordinário e Pleitos','CUSTEIO 33903983  SEADE',NULL,'6900,36','PLASTIFICAÇÃO, CARIMBOS E ENCADERNAÇÃO','89110103','Contratação de serviços de impressão em grandes formatos, plastificação, encadernação, carimbos e reprografia','Não','','','01/07/25','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','000269777.2024.6.01.8004','755732','Em elaboração dos artefatos da contratação'),
	 (19,'SEADE','Ordinário e Pleitos','CUSTEIO33903946SEADE',NULL,'11344,11','LAVAGEM DE TOGAS, COLETES, TOALHAS DE MESA E CORTINAS','85317132','A contratação de serviço de lavanderia para a higienização de togas, toalhas de mesa, cortinas, cadeiras, sofás e outros itens é essencial para garantir que o Tribunal Regional Eleitoral do Acre (TREAC) mantenha um ambiente institucional limpo, organizado e adequado para o desempenho das atividades do dia a dia.','Não','31/12/25','31/12/2025','30/06/2025','31/12/2025','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade','000160331.2023.6.01.8000','755734','Em elaboração dos artefatos da contratação'),
	 (20,'SEADE','Ordinário','CUSTEIO33903946SEADE',NULL,'6834,54','LAVAGEM DE SOFÁS E CADEIRAS','85317133','A contratação de serviço de lavanderia para a higienização de togas, toalhas de mesa, cortinas, cadeiras, sofás e outros itens é essencial para garantir que o Tribunal Regional Eleitoral do Acre (TREAC) mantenha um ambiente institucional limpo, organizado e adequado para o desempenho das atividades do dia a dia.','Não','','','','','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade','000264666.2024.6.01.8000','755734','Em elaboração dos artefatos da contratação'),
	 (21,'SEADE','Ordinário e Pleitos','CUSTEIO33903702SEADE',NULL,'1510000,00',' LIMPEZA E CONSERVAÇÃO DOS IMÓVEIS DA SEDE E INTERIOR','85324031','Serviços de limpeza e conservação a serem executados nos prédios do TREAC, interior e capital','Não','17/05/26','17/05/27','17/01/24','17/05/26','Alta','Garantia dos direitos fundamentais','000297112.2022.6.01.8000','757635',''),
	 (22,'SEADE','Ordinário','CUSTEIO33903943SEADE',NULL,'821010,00','ENERGIA ELÉTRICA','',' Fornecimento de energia elétrica a ser consumida nos prédios do TREAC, capital e interior do Estado','Não','','','','','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade e Eficiência','000150512.2024.6.01.8000','756894',''),
	 (23,'SEADE','Ordinário','CUSTEIO33903912SEADE',NULL,'91000,00','LOCAÇÃO, EM REGIME DE COMODATO, DE APARELHOS PURIFICADORES/REFRIGERADORES DE ÁGUA','20648','A contratação de serviços de locação de filtros e purificadores de água para os prédios do Tribunal Regional Eleitoral do Acre (TREAC), na capital e no interior, tem como objetivo garantir o fornecimento contínuo de água potável de qualidade para servidores, colaboradores e cidadãos atendidos pelo Tribunal.','Não','13/04/26','13/04/2028','13/12/2025','13/04/2026','Alta','Promoção da sustentabilidade','000285365.2024.6.01.8000','','Será iniciado novo procedimento licitatório, pois o valor do contrato é superior ao praticado no mercado'),
	 (24,'SEADE','Ordinário e Pleitos','CUSTEIO33904014SEADE',NULL,'21200,00','DESPESA COM TELEFONIA MÓVEL PARA A CAPITAL E INTERIOR DO ESTADO','14126387','Despesa com telefonia móvel para a capital e interior do Estado','Não','','','01/08/25','01/01/27','Média','Aperfeiçoamento da gestão administrativa e da governança judiciária','000127334.2023.6.01.8000','','Foi aberto processo 000042746.2025.6.01.8000 para identificar se a contratação ainda é necessária'),
	 (25,'SEADE','Ordinário','CUSTEIO33903978SEADE',NULL,'110000,00','SERVIÇOS ESPECIALIZADOS DE CONTROLE DE PRAGAS URBANAS, INCLUINDO DEDETIZAÇÃO, DESINSETIZAÇÃO, DESRATIZAÇÃO E DESCUPINIZAÇÃO','9433417','A contratação de serviços especializados de controle de insetos e animais sinantrópicos nocivos visa garantir a higiene, a segurança e a preservação do patrimônio público em todas as unidades do Tribunal Regional Eleitoral do Acre (TREAC), abrangendo imóveis da capital e do interior. A execução periódica desses serviços é essencial para evitar infestações e minimizar os riscos à saúde ocupacional, além de prevenir danos estruturais que podem gerar custos adicionais para a Administração.','Não','','','01/06/2025','07/01/2026','Alta','Garantia dos direitos fundamentais','000215156.2023.6.01.8000','755724','Equipe de Planejamento está elaborando os artefatos'),
	 (26,'SEADE','Ordinário e Pleitos','CUSTEIO33903705SEADE',NULL,'160000,00',' SERVIÇOS DE COPEIRAGEM E GARÇOM','14397','A contratação dos serviços de copa e garçom é essencial para garantir o suporte logístico e organizacional necessário às atividades institucionais do Tribunal Regional Eleitoral do Acre (TREAC) e dos cartórios eleitorais da capital, assegurando eficiência operacional, conformidade com normas sanitárias e otimização do atendimento a autoridades, servidores e público externo.','Não','09/05/27','09/05/27','09/01/26','09/05/27','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','000284928.2024.6.01.8000','755740','Processo em fase de prorrogação'),
	 (27,'SEMAP','Ordinário','CUSTEIO33903007SEMAP',NULL,'30000,00',' GÊNEROS DE ALIMENTAÇÃO (AÇÚCAR, CAFÉ EM PÓ, ADOÇANTE E CHÁ)','89407963','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (28,'SEMAP','Ordinário e Pleitos','CUSTEIO33903016SEMAP',NULL,'95000,00',' MATERIAL DE EXPEDIENTE (PAPEL A4, CANETA, BLOCO DE PAPEL, ENVELOPE, CLIPE, PINCEL, TESOURA, COLA LÍQUIDA)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699',''),
	 (29,'SEMAP','Ordinário e Pleitos','CUSTEIO33903026SEMAP',NULL,'28200,00','MATERIAL ELÉTRICO E ELETRÔNICO (PILHA, FILTRO DE LINHA, EXTENSÃO ELÉTRICA)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699',''),
	 (30,'SEMAP','Ordinário e Pleitos','CUSTEIO33903017SEMAP',NULL,'18000,00',' MATERIAIS DE CONSUMO DE PROCESSAMENTO DE DADOS (PENDRIVE, TONNER PARA IMPRESSORA, KIT TECLADO/MOUSE SEM FIO)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699',''),
	 (31,'SEMAP','Ordinário e Pleitos','CUSTEIO33903019SEMAP ',NULL,'6000,00','MATERIAL DE ACONDICIONAMENTO E EMBALAGEM (FITA GOMADA, SACOLA PERSONALIZADA)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699',''),
	 (32,'SEMAP','Ordinário e Pleitos','CUSTEIO33903028SEMAP',NULL,'17100,00','MATERIAL DE PROTEÇÃO E SEGURANÇA (CADEADO, CORDA EM POLIPROPENO)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','761699',''),
	 (33,'SEMAP','Ordinário e Pleitos','CUSTEIO33903021SEMAP ',NULL,'8700,00','MATERIAL COPA E COZINHA (TOALHA DE PAPEL, COPO DESCARTÁVEL BIODEGRADÁVEL)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','000270117.2024.6.01.8000','761699','Em fase de contratação'),
	 (34,'SEMAP','Ordinário e Pleitos','CUSTEIO33903022SEMAP  ',NULL,'13755,00',' MATERIAL DE LIMPEZA E PRODUTOS DE HIGIENIZAÇÃO (ÁGUA SANITÁRIA, ÁLCOOL PARA LIMPEZA, DESINFETANTE, DETERGENTE, SABÃO, PAPEL HIGIÊNICO, SABONETE LÍQUIDO, SACO PARA LIXO)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','000270117.2024.6.01.8000','761699','Em fase de contratação'),
	 (35,'SEMAP','Ordinário e Pleitos','CUSTEIO33903022SEMAP  ',NULL,'5105,00','FERRAMENTAS EM GERAL (CHAVE PHILIPS, ALICATE DE CORTE, CHAVE DE TESTE)','','Garantir o estoque do almoxarifado ao longo do ano de 2026, para atender as demandas da secretaria e das zonas eleitorais do Tribunal','Não','','','01/08/2025','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','','',''),
	 (36,'SECON','Ordinário','CUSTEIO33903901SECON ',1,'11988,00','LICENÇA DE ACESSO A SISTEMA DE APURAÇÃO E RETENÇÃO NA FONTE DE TRIBUTOS  GT FÁCIL','61223108','Contratação de serviço de consulta online da tributação na fonte por tipo de serviço ','Não','11/04/26','11/04/2026','01/02/2026','12/04/2026','Média','Aperfeiçoamento da gestão administrativa e da governança judiciária','','753381','000041884.2025.6.01.8000'),
	 (37,'SETRAN','Ordinário e Pleitos','CUSTEIO33903001SETRAN ',NULL,'310000,00',' COMBUSTÍVEIS E LUBRIFICANTES AUTOMOTIVOS','914019740','Abastecimento da frota do Tribunal','Não','10/01/28','10/01/28','10/09/27','10/01/28','Alta','Fortalecimento da relação institucional com a sociedade Aperfeiçoamento da gestão administrativa e da governança judiciária Aperfeiçoamento da gestão orçamentária e financeira','000017980.2025.6.01.8000','750204','Processo de prorrogação iniciado');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (37,'SETRAN','Ordinário e Pleitos','CUSTEIO33903039SETRAN ',NULL,'80000,00',' PEÇAS AUTOMOTIVAS','','Materiais de reposição nos veículos da frota do Tribunal','Não','11/01/28','11/01/28','11/09/27','10/01/28','Alta','Fortalecimento da relação institucional com a sociedade Aperfeiçoamento da gestão administrativa e da governança judiciária Aperfeiçoamento da gestão orçamentária e financeira','000017980.2025.6.01.8001','750204','Processo de prorrogação iniciado'),
	 (37,'SETRAN','Ordinário e Pleitos','CUSTEIO33903919SETRAN',NULL,'60000,00','MANUTENÇÃO PREVENTIVA E CORRETIVA','8713565','Manutenção preventiva e corretiva','Não','12/01/28','12/01/28','12/09/27','10/01/28','Alta','Fortalecimento da relação institucional com a sociedade Aperfeiçoamento da gestão administrativa e da governança judiciária Aperfeiçoamento da gestão orçamentária e financeira','000017980.2025.6.01.8002','750204','Processo de prorrogação iniciado'),
	 (38,'SETRAN','Ordinário e Pleitos','CUSTEIO33903301SETRAN',NULL,'745000,00','PASSAGENS AÉREAS','25828','Aquisição de passagens aéreas','Não','11/10/25','11/08/25','01/08/24','11/10/25','Alta','Fortalecimento da relação institucional com a sociedade Melhoria da gestão de pessoas Aperfeiçoamento da gestão administrativa e da governança judiciária Aperfeiçoamento da gestão orçamentária e financeira','000064511.2024.6.01.8000','','Atentar para o prazo de prorrogação do contrato'),
	 (39,'SETRAN','Ordinário e Pleitos','CUSTEIO33903701SETRAN ',NULL,'690000,00','SERVIÇO DE MOTORISTA','85115008','Contratação de empresa para prestação do serviço de condução dos veículos do Tribunal e da Zona Eleitoral','Não','06/03/26','06/03/35','06/12/25','06/03/25','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','000146275.2024.6.01.8000','750207',''),
	 (40,'SETRAN','Ordinário','CUSTEIO33903969SETRAN ',NULL,'77000,00',' SEGURO GERAL DE VEÍCULOS','71330127','Segurar a frota do Tribunal em eventuais sinistros','Não','','','','07/01/2026','Médio','Aperfeiçoamento da gestão administrativa e da governança judiciária','000107390.2024.6.01.8000','','Equipe de Planejamento da Contratação'),
	 (42,'SLC','Ordinário','CUSTEIO33903947SLC',NULL,'15000,00','PUBLICAÇÃO DE AVISOS DE LICITAÇÕES, EDITAIS DE DOAÇÃO EM JORNAL LOCAL','89110049','Publicação de avisos de licitações, editais de doação em jornal local','Não','','','07/01/2026','10/05/2026','Ata','Garantia dos direitos fundamentais','000261024.2024.6.01.8000','','Em fase de contratação'),
	 (43,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'2000000,00','REFORMA DO 4º ANDAR DA SEDE','5451627','Necessidade de reforma para atender quesitos de ocupação do 4º andar do Prédio do Tribunal, visando otimizar ambientes de trabalho e de qualificação profissional gerando maior eficiência das atividades desenvolvidas pela Justiça Eleitoral.','Não','','','02/07/2026','','Média','Fortalecimento da relação institucional com a sociedade Agilidade e produtividade na prestação jurisdicional Promoção da sustentabilidade','','760570',''),
	 (44,'ASGIM','Ordinário','CUSTEIO 339039 ASGIM',NULL,'4000,00','LIMPEZA DO ESTAÇÃO DE TRATAMENTO DE ESGOTO','85325194','Necessidade de limpeza dos sistemas de tratamento de efluentes sanitários pertencentes ao TREAC na Capital.','Não','','','30/06/2025','','Média','Promoção da sustentabilidade','','760590',''),
	 (45,'ASGIM','Ordinário','CUSTEIO33903669 ASGIM',NULL,'64000,00','SEGURO PREDIAL','71330126','Necessidade de contratação de seguro predial para os ambientes tidos como depósitos de urnas eletrônicas  Rio Branco e Cruzeiro do Sul  conforme normativa determinada pela Justiça Eleitoral.','Não','','','01/04/2026','','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','','760589',''),
	 (46,'ASGIM','Ordinário','CUSTEIO 33903606  ASGIM',NULL,'90000,00','PROJETOS CAPITAL E INTERIOR','83320060',' Elaboração de projetos arquitetônicos e complementares  Capital e Interior','Não','','','30/06/2025','','Média','Promoção da sustentabilidade','','760588','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (47,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'291000,00','REFORMA DO FÓRUM DA 3ª ZONA ELEITORAL','5451627','Necessidade de reforma para atender quesitos de conservação do imóvel e otimizar ambientes de trabalho de modo a gerar maior eficiência das atividades desenvolvidas pela Justiça Eleitoral.','Não','','','30/06/2026','','Média','Fortalecimento da relação institucional com a sociedade Agilidade e produtividade na prestação jurisdicional Promoção da sustentabilidade','','760558',''),
	 (48,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'104000,00','REFORMA DO FÓRUM DO PAE DE BUJARI','5451627','Necessidade de reforma para atender quesitos de conservação do imóvel e otimizar ambientes de trabalho de modo a gerar maior eficiência das atividades desenvolvidas pela Justiça Eleitoral.','Não','','','30/06/2026','','Média','Fortalecimento da relação institucional com a sociedade Agilidade e produtividade na prestação jurisdicional Promoção da sustentabilidade','','760567',''),
	 (49,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'112000,00','REFORMA DO FÓRUM DO PAE DE PORTO ACRE','5451627','Necessidade de reforma para atender quesitos de conservação do imóvel e otimizar ambientes de trabalho de modo a gerar maior eficiência das atividades desenvolvidas pela Justiça Eleitoral.','Não','','','01/07/2026','','Média','Fortalecimento da relação institucional com a sociedade Agilidade e produtividade na prestação jurisdicional Promoção da sustentabilidade','','760569',''),
	 (50,'ASGIM','Ordinário','CUSTEIOASGIM',NULL,'7800,00','AQUISIÇÃO DE SOFTWARE DE ORÇAMENTO E/OU PLANEJAMENTO DE OBRAS DE ENGENHARIA','18227502','Necessidade de softwares que auxiliem o desenvolvimento de atividades relacionadas a engenharia, gerando maior eficiência e produtividade deste Setor de Engenharia.','Não','','','01/08/2026','','Média','Aperfeiçoamento da gestão administrativa e da governança judiciária','','760591',''),
	 (51,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'410000,00',' MANUTENÇÃO DE APARELHOS DE AR CONDICIONADO E CENTRAIS DE AR  SEDE','87118619','A manutenção regular dos sistemas de ar condicionado e de renovação de ar é essencial para garantir o bom funcionamento e a segurança das instalações, bem como proporcionar um ambiente confortável e saudável para os usuários. A ausência de manutenção adequada pode resultar em falhas operacionais, perda de eficiência energética, aumento dos custos de operação e degradação prematura dos equipamentos.','Não','14/01/26','14/10/2025','14/01/2036','14/01/2026','Alta','Garantia dos direitos fundamentais/Promoção da sustentabilidade','000244222.2024.6.01.8000','760575',''),
	 (52,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'30000,00',' MANUTENÇÃO DE ELEVADORES','87116691','Contratação de empresa especializada como forma de garantir o perfeito funcionamento do elevador instalado no EdifícioSede do Tribunal Regional Eleitoral do Acre, proporcionando condições ideais de funcionalidade e segurança nos deslocamentos dos servidores, terceirizados e eleitores que visitem o edifício.','Não','16/10/25','16/07/2028','16/07/2025','16/10/2025','Alta','Promoção da sustentabilidade Melhoria da gestão de pessoas Aperfeiçoamento da gestão administrativa e da governança judiciária','000167314.2024.6.01.8000','760579','Atentar para o prazo de prorrogação'),
	 (53,'ASGIM','Ordinário','CUSTEIO33903916ASGIM',NULL,'700000,00','MANUTENÇÃO PREDIAL','5451627','Contratação necessária pra manutenção preventiva com intuito de manter boas condições de funcionamento na capital e interior','Não','29/01/26','29/01/2029','29/10/2025','29/01/2026','Alta','Agilidade e produtividade na prestação jurisdicional/Promoção da sustentabilidade','000249078.2024.6.01.8000','760581',''),
	 (54,'ASGIM','Ordinário','CUSTEIO  33903701 ASGIM',NULL,'50000,00','COMUNICAÇÃO VISUAL: SEDE, FÓRUNS E POSTOS DE ATENDIMENTO  CAPITAL E INTERIOR','87321334','Necessidade de implantar comunicação visual nas unidades prediais pertencentes a Justiça Eleitoral na Capital e Interior','Não','','','30/06/2026','','Média',' Fortalecimento da relação institucional com a sociedade Promoção da sustentabilidade Melhoria da gestão de pessoas','','760582',''),
	 (55,'ASGIM','Ordinário','CUSTEIO33903701ASGIM',NULL,'4000,00','APLICAÇÃO DE PELÍCULA FUMÊ EM ESQUADRIAS','5465584','A aplicação de película fumê visa reduzir a incidência de luz solar que adentra as esquadrias nas edificações pertencentes ao Tribunal. ','Não','','','30/06/2026','','Média',' Promoção da sustentabilidade Melhoria da gestão de pessoas','','760585',''),
	 (56,'ASGIM','Ordinário','CUSTEIO33903701 ASGIM',NULL,'56000,00','MANUTENÇÃO E/OU AMPLIAÇÃO DO SISTEMA FOTOVOLTAICO IMPLATANDO NA SEDE DO TRIBUNAL','87119747','Necessidade de manutenção do sistema fotovoltaico instalado.','Não','','','30/06/2026','','Média','Promoção da sustentabilidade','','760586','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (57,'SGEC','Ordinário e Pleitos','CUSTEIO33903701SGEC',NULL,'330236,94',' SERVIÇO DE CARREGADORES','85914389','Existe demanda permanente do serviço de remoção e carregamento de bens móveis e materiais de consumo entre as diversas unidades administrativas do TRE/AC, de modo que essa atividade se revela imprescindível para o bom andamento dos serviços.','Não','30/10/25','30/10/2028','01/07/2025','30/10/2025','Alta','Melhoria da gestão de pessoas Aperfeiçoamento da gestão administrativa e da governança judiciária Aperfeiçoamento da gestão orçamentária e financeira','000005046.2023.6.01.8000','761686',''),
	 (58,'SGEC','Ordinário e Pleitos','CUSTEIO33903701SGEC',NULL,'2500650,19','APOIO ADMINISTRATIVO','9115380','Prestação de serviços comuns e continuados de assistência administrativa','Não','15/01/26','15/01/29','','07/01/25','Alta','Garantia dos direitos fundamentais','000239463.2024.6.01.8000','',''),
	 (59,'NISIPJ','Ordinário e Pleitos','CUSTEIO33903701NISIPJ',NULL,'221525,89',' SERVIÇO DE RECEPCIONISTAS','8518729','Controle de acesso de pessoas, promovendo a identificação e registro dos visitantes','Não','18/04/26','18/04/2027','01/12/2024','18/04/2026','Alta',' Fortalecimento da relação institucional com a sociedade','000226643.2024.6.01.8000','','Em fase de prorrogação'),
	 (60,'SEADE','Ordinário e Pleitos','CUSTEIO33903958SEADE',NULL,'134000,00',' TELEFONIA FIXA ','14126107','Essencial para comunicação interna e externa do Tribunal','Não','29/05/26','29/05/35','29/01/25','29/05/26','Alta','Fortalecimento da relação institucional com a sociedade','000049445.2024.6.01.8000','','000038412.2025.6.01.8000  processo de prorrogação iniciado'),
	 (61,'SEADE','Ordinário','CUSTEIO33903004SEADE',NULL,'8700,00','RECARGA EXTINTORES','8723662','A recarga de extintores de incêndio é uma medida essencial para garantir que os extintores nos prédios do Tribunal Regional Eleitoral do Acre (TREAC), tanto na capital quanto no interior do estado, estejam sempre operacionais e em conformidade com as normas de segurança contra incêndios.','Não','','','01/01/2026','','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária Promoção da Sustentabilidade e Eficiência ','000288570.2024.6.01.8000','756465','Em fase de planejamento'),
	 (62,'NISIPJ','Ordinário','CUSTEIO33903977NISIPJ',NULL,'488500,00',' VIGILÂNCIA OSTENSIVA/MONITORADA/RASTREAMENTO','85223868','Contratação de serviço de vigilância para maior proteção dos edifícios que abrigam o Tribunal','Não','','','','07/01/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','000071596.2022.6.01.8000','','Em fase de ajustes'),
	 (63,'NISIPJ','Ordinário e Pleitos','CUSTEIO33903703NISIPJ',NULL,'2761147,81','VIGILÂNCIA DESARMADA E ARMADA','852-24015 ','Os vigilantes desarmados atuarão no controle de entrada, auxiliando na passagem pelos portais detectores de metais, e nos serviços de monitoramento das câmeras','Não','','25/04/2028','01/12/2024','26/04/2025','Alta',' Aperfeiçoamento da gestão administrativa e da governança judiciária','','','Contratos n. 03/2024 (0636596)-- Contrato n. 04/2024 (0636636)-- Contrato n. 15/2023 (0607398)-- Contrato n. 14/2023 (0607356)-- Contrato n. 06/2023 (0579025)'),
	 (64,'STI','Ordinário','CUSTEIO-33903917-STI',NULL,'120000,00','MANUTENÇÃO PREVENTIVA E CORRETIVA DOS DATA CENTERS','166-27740','A garantia dos Data Centers modulares adquiridos pelo Tribunal se encerra em meados de 2025 e será necessário contratar uma empresa para que seja dada continuidade à manutenção preventiva e corretiva dos equipamentos.','Não','','','','','Alta','Agilidade e produtividade na prestação jurisdicional--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados','','','Foi aberto procedimento 0000427-46.2025.6.01.8000 para verificar se ainda será necessário'),
	 (65,'STI','Ordinário','CUSTEIO-33904013-STI ',NULL,'40000,00','COMUNICAÇÃO DE DADOS: LINKS DE DADOS SECUNDÁRIO - SEDE DO TRIBUNAL','142-26506','Comunicação de dados: Links de dados secundário - Sede do Tribunal','Não','20/07/25','20/07/2028','20/02/2025','20/07/2025','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','0000896-97.2022.6.01.8000','751693',''),
	 (66,'STI','Ordinário','CUSTEIO-33904013-STI ',NULL,'40000,00','COMUNICAÇÃO DE DADOS: LINKS DE DADOS PRINCIPAL - SEDE DO TRIBUNAL','142-26506','Comunicação de dados: Links de dados principal - Sede do Tribunal','Não','20/07/25','20/07/2028','20/02/2025','20/07/2025','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','','','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (67,'STI','Ordinário','CUSTEIO-33903701-STI ',NULL,'360000,00','COMUNICAÇÃO DE DADOS: BACKBONE SECUNDÁRIO - BACKUP E ITINERANTES - SATELITAL','142-26565','Continuidade de serviços contratados – links de comunicação principal e de contingência TSE-TRE-Cartórios (Backbone Secundário)','Não','17/01/26','17/01/2035','17/09/2025','17/01/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','0001644-66.2021.6.01.8000','751693',''),
	 (68,'STI','Ordinário','CUSTEIO-33904013-STI ',NULL,'162000,00',' COMUNICAÇÃO DE DADOS SEDE, CARTÓRIOS E PAES (BACKBONE)','142-26506','Continuidade de serviços contratados (links de comunicação principal  e de contingência TSE-TRE-Cartórios)','Não','01/02/27','01/02/2027','01/11/2026','01/02/2027','Alta','Agilidade e produtividade na prestação jurisdicional','0002514-14.2021.6.01.8000','751693',''),
	 (69,'STI','Pleitos','CUSTEIO-33904001-STI ',NULL,'150000,00','MANUTENÇÃO PREVENTIVA DAS URNAS ELETRÔNICAS','-','O Tribunal Superior Eleitoral (TSE) exige a execução das atividades de manutenção preventiva e tal exigência é feita com base nas recomendações repassadas pela Coordenadoria de Tecnologia Eleitoral - COTEL, daquele Tribunal Superior.  A Justiça Eleitoral não dispõe em seu quadro de pessoal de servidores, nem em número suficiente e nem, legalmente, com atribuições específicas para suprir a demanda de atividades envolvidas na conservação das urnas.  Dessa forma, foi contratada uma empresa para realizar as manutenções necessárias, atendendo nos 2 (dois) locais de armazenamento de urnas eletrônicas do TRE/AC. Portanto, trata-se, em última análise, da continuidade desse importante serviço.','Sim','26/05/26','26/01/2027','08/01/2026','26/05/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','0000215-59.2024.6.01.8000','751698',''),
	 (70,'STI','Ordinário','CUSTEIO-339030-STI',NULL,'10000,00','LICENÇA ANUAL CANVA','182-27502','A contratação é necessária para suprir as demandas por softwares inseridas no Levantamento de Necessidades por Soluções de TI (Processo SEI n. 0002755-80.2024.6.01.8000) conforme se depreende da consolidação inserida no Despacho GSTI 0758463, bem como pela necessidade de continuidade do uso do Microsoft Office 365 (Processo SEI n. 0001548-17.2022.6.01.8000).','Não','','','01/02/26','01/06/26','Alta','Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751700','Equipe de Planejamento da Contratação'),
	 (71,'STI','Ordinário','CUSTEIO-339030-STI',NULL,'273000,00','MICROSOFT OFFICE 365','182-27502','A contratação é necessária para suprir as demandas por softwares inseridas no Levantamento de Necessidades por Soluções de TI (Processo SEI n. 0002755-80.2024.6.01.8000) conforme se depreende da consolidação inserida no Despacho GSTI 0758463, bem como pela necessidade de continuidade do uso do Microsoft Office 365 (Processo SEI n. 0001548-17.2022.6.01.8000).','Não','','','02/02/26','02/06/26','Alta','Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751700',''),
	 (72,'STI','Ordinário','CUSTEIO-339030-STI',NULL,'2000,00','WHATAUTO','-','A contratação é necessária para suprir as demandas por softwares inseridas no Levantamento de Necessidades por Soluções de TI (Processo SEI n. 0002755-80.2024.6.01.8000) conforme se depreende da consolidação inserida no Despacho GSTI 0758463, bem como pela necessidade de continuidade do uso do Microsoft Office 365 (Processo SEI n. 0001548-17.2022.6.01.8000).','Não','','','03/02/26','03/06/26','Alta','Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751700',''),
	 (73,'STI','Ordinário','CUSTEIO-339030-STI',NULL,'15000,00','APLICATIVO PARA REGISTRO DE PONTO PELO SMARTPHONE','-','A contratação é necessária para suprir as demandas por softwares inseridas no Levantamento de Necessidades por Soluções de TI (Processo SEI n. 0002755-80.2024.6.01.8000) conforme se depreende da consolidação inserida no Despacho GSTI 0758463, bem como pela necessidade de continuidade do uso do Microsoft Office 365 (Processo SEI n. 0001548-17.2022.6.01.8000).','Não','','','04/02/26','04/06/26','Alta','Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751700',''),
	 (74,'STI','Ordinário','CUSTEIO-339030-STI',NULL,'18000,00','MINI FIREWALL','-','Necessidade de realizar conexão VPN com o ambiente do TRE/AC para fins de acesso aos sistemas eleitorais a partir de locais remotos, em ações de atendimento itinerante ao eleitor.','Não','','','07/01/26','31/01/26','Média','Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados.','','751962',''),
	 (75,'1ªZE','Ordinário','CUSTEIO-33903701-1ªZE',12,'390000,00','SERVIÇO DE DIGITADORES','-','Suporte nas atividades de atendimento ao público na CAE e OCA','Não','28/03/26','18/04/2027','18/01/2026','28/03/2026','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária','0002874-14.2024.6.01.8009','',''),
	 (76,'1ªZE','Ordinário','CUSTEIO-33903978-1ªZE',12,'6000,00','SERVIÇOS DE CAPINA/ROÇAGEM','853-14044','Manutenção do zelo e das boas condições de trabalho no Posto de Atendimento Eleitoral - PAE de Porto Acre','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','0000069-78.2025.6.01.8000','751507','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (77,'1ªZE','Ordinário','CUSTEIO-33903004-1ª ZE',2,'340,00','GÁS DE COZINHA','461517','Atender às necessidades diárias de consumo dos servidores, funcionários terceirizados e visitantes, e pessoas que procuram atendimento junto ao PAE Porto Acre','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Fortalecimento da relação institucional com a sociedade--- Promoção da sustentabilidade---','-','751494',''),
	 (78,'2ªZE','Ordinário','CUSTEIO-33903004-2ª ZE',2,'270,00','GÁS DE COZINHA','461517','O gás de cozinha é necessário para uso do fogão do Cartório, com o fim de realizar preparo de refeições e bebidas (café, chá, etc) para servidores e convidados.','Não','','','03/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','-','752195',''),
	 (79,'3ªZE','Ordinário','CUSTEIO-33903004-3ªZE',2,'300,00','GÁS DE COZINHA','461517','O gás de cozinha é necessário para abastecimento do fogão da 3ª Zona, com o fim de realizar preparo de refeições e bebidas (café, chá, etc) para servidores e convidados','Não','','','03/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','-','754134',''),
	 (80,'4ªZE','Ordinário','CUSTEIO-33903004-4ªZE',5,'630,00','GÁS DE COZINHA','461517','Atender às necessidades diárias de consumo dos servidores, eleitores e cidadãos que procuram atendimento na 4ZE (Sede e PAE''s).','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais','-','757464',''),
	 (81,'5ªZE','Ordinário','CUSTEIO-33903004-5ªZE',4,'480,00','GÁS DE COZINHA','461517','Viabilizar o uso do fogão no Cartório, com o fim de preparar refeições e bebidas (café, chá, etc) para servidores e convidados em Tarauacá','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Fortalecimento da relação institucional com a sociedade--- Promoção da sustentabilidade--- Promoção da sustentabilidade---','-','757050',''),
	 (82,'5ªZE','Ordinário','CUSTEIO-33903004-5ªZE',2,'400,00','GÁS DE COZINHA','461517','Viabilizar o uso do fogão no Cartório, com o fim de preparar refeições e bebidas (café, chá, etc) para servidores e convidados em Jordão','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Fortalecimento da relação institucional com a sociedade--- Promoção da sustentabilidade--- Promoção da sustentabilidade---','-','',''),
	 (83,'5ªZE','Ordinário','CUSTEIO-33903978-5ªZE',NULL,'4320,00','CAPINA E ROÇAGEM EM JORDÃO','853-14044','Manter a área externa do Cartório Eleitoral limpa, acessível e organizada. A realização do serviço quinzenalmente manterá o mato sempre baixo, com aspecto de cuidado e zelo com o prédio.','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','','757051',''),
	 (84,'5ªZE','Ordinário','CUSTEIO-33903926-5ªZE',NULL,'1000,00','TRANSPORTE DE MERCADORIA POR AVIÃO - TRECHO TARAUACÁ A JORDÃO','-','Atender às necessidades que surgem no PAE de Jordão e que são supridas com o envio, através de avião, de bens permanentes ou de consumo para reposição, troca ou devolução, a partir de Tarauacá ou Rio Branco.','Não','','','01/11/2025','07/01/2026','Alta','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','','757216',''),
	 (85,'6ªZE','Ordinário','CUSTEIO-33903004-6ªZE',2,'300,00','GÁS DE COZINHA','461517','O gás de cozinha é necessário para abastecimento do fogão da 6ª Zona, com o fim de realizar preparo de refeições e bebidas (café, chá, etc) para servidores e convidados.','Não','','','03/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais--- Promoção da sustentabilidade---','-','752898',''),
	 (86,'7ªZE','Ordinário','CUSTEIO-33903004-7ªZE',3,'450,00','GÁS DE COZINHA','461517','O gás de cozinha é necessário para abastecimento do fogão da 7ª Zona, com o fim de realizar preparo de refeições e bebidas (café, chá, etc) para servidores e convidados.','Não','','','01/11/2025','07/01/2026','Média','Promoção da sustentabilidade---','-','754390','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (87,'8ªZE','Ordinário','CUSTEIO-33903004-8ªZE',2,'280,00','GÁS DE COZINHA','461517','Atender às necessidades diárias de consumo dos servidores, funcionários terceirizados e visitantes','Não','','','01/11/2025','07/01/2026','Média','Garantia dos direitos fundamentais','-','',''),
	 (88,'ASSAI','Ordinário','CUSTEIO-33903701-ASSAI',NULL,'17000,00','CONTRATAÇÃO DE EMPRESA DE VERIFICAÇÃO E VALIDAÇÃO DE INVENTÁRIO DE GASES DE EFEITO ESTUFA (GEE)','-','Redução dos impactos ambientais das atividades do TRE/AC. 

O compromisso com a neutralização das emissões reafirma o papel do Tribunal na construção de um futuro mais equilibrado e ambientalmente responsável, contribuindo ativamente para os esforços globais de combate às mudanças climáticas.','Não','','','01/03/2026','30/11/2026','Alta',' Promoção da sustentabilidade---','-','761966',''),
	 (89,'ASSAI','Ordinário','CUSTEIO-ASSAI',NULL,'926,25','AQUISIÇÃO DE CERTIFICADO DE ENERGIA RENOVÁVEL (I REC) COM EMISSÃO ZERO DE GEE','-','Redução dos impactos ambientais das atividades do TRE/AC. 

O compromisso com a neutralização das emissões reafirma o papel do Tribunal na construção de um futuro mais equilibrado e ambientalmente responsável, contribuindo ativamente para os esforços globais de combate às mudanças climáticas.','Não','','','01/03/2026','30/11/2026','Alta',' Promoção da sustentabilidade---','-','761966',''),
	 (110,'VP ','Pleitos','CUSTEIO-33903959-VOTAÇÃO PARALELA',NULL,'120000,00','SERVIÇOS DE AUDIO, VÍDEO E FOTO 1º E 2º TURNO','-','Garantir lisura no proecsso eleitoral','Sim','','','01/02/24','01/06/24','Alto','Fortalecimento da relação institucional com a sociedade','0002005-15.2023.6.01.8000','-',''),
	 (90,'ASSAI','Ordinário','CUSTEIO-ASSAI',NULL,'2250,00','AQUISIÇÃO DE CESSÃO DE DIREITO DE CRÉDITO DE CARBONO','-','Redução dos impactos ambientais das atividades do TRE/AC. 

O compromisso com a neutralização das emissões reafirma o papel do Tribunal na construção de um futuro mais equilibrado e ambientalmente responsável, contribuindo ativamente para os esforços globais de combate às mudanças climáticas.','Não','','','01/03/2026','30/11/2026','Alta',' Promoção da sustentabilidade---','-','761966',''),
	 (91,'ASPLAN','Pleitos','CUSTEIO-33903979-ASPLAN',NULL,'50000,00','PESQUISA DE OPINIÃO PÚBLICA',' 837-15342 ','Pesquisa de opinião pública','Não','','','01/11/2025','01/06/2026','Alta','Fortalecimento da relação institucional com a sociedade','-','-','-'),
	 (92,'SPCE','Pleitos','CUSTEIO-33903912-SPCE',NULL,'10000,00','ALUGUEL DE CLIMATIZADORES',' 732-20818 ','Locação de climatizadores para uso no fechamento de cadastro','Não','','','01/11/2025','01/04/2025','Alta','Fortalecimento da relação institucional com a sociedade','-','-','-'),
	 (93,'SETRAN','Pleitos','CUSTEIO-33903974-SETRAN',NULL,'560000,00','TRANSPORTE DE URNAS ELETRÔNICAS',' 643-22730 ','Prestação de serviços de transporte de urnas eletrônicas -1º e 2º turnos','Não','','','01/02/26','02/05/26','Alta','Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária.','-','750213',''),
	 (94,'SETRAN','Pleitos','CUSTEIO-33903305-SETRAN',NULL,'262832,76','LOCAÇÃO DE MEIO DE TRANSPORTE ',' 732-25089 ','Atendimento das demandas da secretaria e zonas eleitorais durante o pleito de 2026','Não','','','01/02/26','02/05/26','Alta','Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária.','','',''),
	 (95,'ASCOM','Pleitos','CUSTEIO-33903993-ASCOM',500,'5000,00','BANNER SOB MEDIDA',' 891-25054 ','A realização das Eleições Gerais de 2026, conduzida pelo Tribunal Regional Eleitoral do Acre (TRE-AC), demanda uma série de ações de comunicação visual para atender a todas as etapas do Calendário Eleitoral, que demanda muita divulgação e orientação (A todos os envolvidos). No dia da eleição, há a necessidade de realizar uma sinalização nos locais de votação, cartórios eleitorais e demais espaços vinculados à logística e à execução do pleito. Essa necessidade é histórica e recorrente em todos os anos eleitorais, sendo prevista nos manuais operacionais, planos de comunicação e orientações técnicas do Tribunal Superior Eleitoral (TSE).','Não','','','01/12/25','01/02/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756921 e 0752522','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (96,'ASCOM','Pleitos','CUSTEIO-33903059-ASCOM',200,'5000,00','ADESIVO PROPAGANDA EM VINIL AUTOCOLANTE',' 891-18961 ','A realização das Eleições Gerais de 2026, conduzida pelo Tribunal Regional Eleitoral do Acre (TRE-AC), demanda uma série de ações de comunicação visual para atender a todas as etapas do Calendário Eleitoral, que demanda muita divulgação e orientação (A todos os envolvidos). No dia da eleição, há a necessidade de realizar uma sinalização nos locais de votação, cartórios eleitorais e demais espaços vinculados à logística e à execução do pleito. Essa necessidade é histórica e recorrente em todos os anos eleitorais, sendo prevista nos manuais operacionais, planos de comunicação e orientações técnicas do Tribunal Superior Eleitoral (TSE).','Não','','','01/12/25','01/02/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756921 e 0752523',''),
	 (97,'ASCOM','Pleitos','CUSTEIO-33903059-ASCOM',150,'10000,00','ADESIVO PROPAGANDA CONFECCIONADO EM PAPEL ADESIVO',' 891-18961 ','A realização das Eleições Gerais de 2026, conduzida pelo Tribunal Regional Eleitoral do Acre (TRE-AC), demanda uma série de ações de comunicação visual para atender a todas as etapas do Calendário Eleitoral, que demanda muita divulgação e orientação (A todos os envolvidos). No dia da eleição, há a necessidade de realizar uma sinalização nos locais de votação, cartórios eleitorais e demais espaços vinculados à logística e à execução do pleito. Essa necessidade é histórica e recorrente em todos os anos eleitorais, sendo prevista nos manuais operacionais, planos de comunicação e orientações técnicas do Tribunal Superior Eleitoral (TSE).','Não','','','01/12/25','01/02/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756921 e 0752524',''),
	 (98,'ASCOM','Pleitos','CUSTEIO-33903044-ASCOM',50000,'10000,00','CARTAZ, FORMATO A3',' 891-4367 ','A realização das Eleições Gerais de 2026, conduzida pelo Tribunal Regional Eleitoral do Acre (TRE-AC), demanda uma série de ações de comunicação visual para atender a todas as etapas do Calendário Eleitoral, que demanda muita divulgação e orientação (A todos os envolvidos). No dia da eleição, há a necessidade de realizar uma sinalização nos locais de votação, cartórios eleitorais e demais espaços vinculados à logística e à execução do pleito. Essa necessidade é histórica e recorrente em todos os anos eleitorais, sendo prevista nos manuais operacionais, planos de comunicação e orientações técnicas do Tribunal Superior Eleitoral (TSE).','Não','','','01/12/25','01/02/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756921 e 0752525',''),
	 (107,'AGEL','Pleitos','CUSTEIO- 33903045- AGEL',10200,'23000,00','MANUAL DO MESÁRIO','484272','Garantir que os mesários tenham todas as intruções necessárias para realizar corretamente as atividades na seção eleitoral. ','Sim','','','07/01/26','01/06/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade---','-','753950',''),
	 (108,'AGEL','Pleitos','CUSTEIO- 33903045- AGEL',5600,'1200,00','GUIA RÁPIDO MÊSÁRIO','235927','Garantir que os mesários tenham todas as intruções necessárias para realizar corretamente as atividades na seção eleitoral. ','Sim','','','07/01/26','01/06/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade---','-','753950',''),
	 (99,'ASCOM','Pleitos','CUSTEIO-33903044-ASCOM',30000,'10000,00','CARTAZ, Formato: 10,5x14,8cm (fechado) | 42x14,8cm (aberto)',' 891-4367 ','A realização das Eleições Gerais de 2026, conduzida pelo Tribunal Regional Eleitoral do Acre (TRE-AC), demanda uma série de ações de comunicação visual para atender a todas as etapas do Calendário Eleitoral, que demanda muita divulgação e orientação (A todos os envolvidos). No dia da eleição, há a necessidade de realizar uma sinalização nos locais de votação, cartórios eleitorais e demais espaços vinculados à logística e à execução do pleito. Essa necessidade é histórica e recorrente em todos os anos eleitorais, sendo prevista nos manuais operacionais, planos de comunicação e orientações técnicas do Tribunal Superior Eleitoral (TSE).','Não','','','01/12/25','01/02/26','Alto','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756921 e 0752526',''),
	 (100,'ASCOM','Pleitos','CUSTEIO-33903993-ASCOM',NULL,'37000,00','OUTDOOR',' 881-14249 ','A Justiça Eleitoral tem como uma de suas missões garantir ampla divulgação de informações oficiais sobre o processo eleitoral, contribuindo para a transparência, a orientação do eleitor e a promoção da participação cidadã. Esse papel de comunicação social se torna ainda mais estratégico em períodos eleitorais, quando a sociedade precisa receber informações claras, seguras e acessíveis sobre o pleito. 
Para alcançar esse público de forma massiva, o uso de outdoors e busdoors é uma estratégia comprovadamente eficaz. Esses meios permitem comunicação de alta visibilidade, com ampla cobertura e impacto direto na rotina da população.','Não','','','01/11/25','01/02/26','Alto',' Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','757012',''),
	 (101,'ASCOM','Pleitos','CUSTEIO -33903993 - ASCOM',NULL,'20000,00','BUSDOOR',' - ','A Justiça Eleitoral tem como uma de suas missões garantir ampla divulgação de informações oficiais sobre o processo eleitoral, contribuindo para a transparência, a orientação do eleitor e a promoção da participação cidadã. Esse papel de comunicação social se torna ainda mais estratégico em períodos eleitorais, quando a sociedade precisa receber informações claras, seguras e acessíveis sobre o pleito. 
Para alcançar esse público de forma massiva, o uso de outdoors e busdoors é uma estratégia comprovadamente eficaz. Esses meios permitem comunicação de alta visibilidade, com ampla cobertura e impacto direto na rotina da população.','Não','','','01/11/25','01/02/26','Alto',' Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','',''),
	 (102,'ASCOM','Pleitos','CUSTEIO-33903023-ASCOM',13000,'170000,00','CAMISETAS',' 881-10030 ','A medida é uma estratégia que atende a diversos objetivos institucionais, operacionais e de comunicação do Tribunal Regional Eleitoral do Acre (TRE-AC). A camiseta oficial garante a rápida identificação de mesários(as), auxiliares de eleição e demais colaboradores(as) perante os eleitores e demais atores envolvidos no pleito. Ao adotar uma camiseta personalizada, o TRE reafirma sua identidade institucional, reforça a marca da Justiça Eleitoral e transmite, de forma concreta, uma mensagem de organização, profissionalismo e seriedade. Isso fortalece a percepção pública de que as eleições são conduzidas com planejamento, cuidado e respeito aos padrões institucionais. ','Não','','','01/10/25','01/08/26','Média','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Melhoria da gestão de pessoas--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','','756916',''),
	 (103,'ASCOM','Pleitos','CUSTEIO -33903659 - ASCOM',NULL,'15000,00','SERVIÇO DE PRODUÇÃO DE VÍDEOS INSTITUCIONAIS',' 891-15458 ','O TRE-AC necessita dar publicidade às suas ações e campanhas de forma a facilitar o acesso às informações de caráter público, bem como aprimorar a transparência institucional de acordo com o previsto no plano estratégico.

Embora o TRE-AC disponha de meios de divulgação como diário oficial e disponibilize informações no site, para reforçar a propagação de informações e alcançar um número maior de pessoas atualmente faz-se necessária a divulgação de conteúdo, com fotos profissionais e vídeos para serem utilizados nas redes sociais e no canal do YouTube. ','Não','','','01/10/25','01/08/26','Média',' Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','-','756915','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (104,'ASCOM','Pleitos','CUSTEIO - 33903659- ASCOM',NULL,'15000,00','SERVIÇO DE FOTOGRAFIA',' 838-6050 ','O TRE-AC necessita dar publicidade às suas ações e campanhas de forma a facilitar o acesso às informações de caráter público, bem como aprimorar a transparência institucional de acordo com o previsto no plano estratégico.

Embora o TRE-AC disponha de meios de divulgação como diário oficial e disponibilize informações no site, para reforçar a propagação de informações e alcançar um número maior de pessoas atualmente faz-se necessária a divulgação de conteúdo, com fotos profissionais e vídeos para serem utilizados nas redes sociais e no canal do YouTube. ','Não','','','01/10/25','01/08/26','Média',' Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais--- Fortalecimento da relação institucional com a sociedade--- Agilidade e produtividade na prestação jurisdicional--- Aperfeiçoamento da gestão administrativa e da governança judiciária---','-','756915',''),
	 (105,'ASSAI','Pleitos','CUSTEIO -33903023 - ASSAI',NULL,'3450,00','COLETES DE IDENTIFICAÇÃO',' 8405-15257 ','Garantir a identificação dos coordenadores acessibilidade pelos eleitores com deficiências nos locais de votação.','Não','','','01/03/26','30/08/26','Média','Garantia dos direitos fundamentais--- Fortalecimento da relação institucional com a sociedade---','-','762030',''),
	 (106,'GASAOF','Pleitos','CUSTEIO-33903303-GASAOF',139,'1088692,50','FRETAMENTO DE AERONAVES',' 732-14680 ','Fretamento de aeronaves para atender necessidade de deslocamento de pessoal e material, durante o período eleitoral, para localidades do interior do Estado não servidas por transporte aéreo regular','Não','','','01/12/25','01/07/26','Alto','Garantia dos direitos fundamentais/Agilidade e produtividade na prestação jurisdicional','-','754909',''),
	 (109,'VP ','Pleitos','CUSTEIO-33903905-VOTAÇÃO PARALELA',NULL,'55000,00','AUDITORIA 1º E 2º TURNO','-','Garantir lisura no proecsso eleitoral','Sim','','','01/02/24','01/06/24','Alto','Fortalecimento da relação institucional com a sociedade','0001617-78.2024.6.01.8000','-',''),
	 (111,'STI','Pleitos','CUSTEIO-33903017-STI',NULL,'3250,00','BOBINAS PARA URNAS ELETRÔNICAS','-','Bobinas para urnas eletrônicas','Sim','','','01/10/25','01/06/26','Alta','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043',''),
	 (112,'STI','Pleitos','CUSTEIO-33903016-STI',NULL,'3570,00','MATERIAL DE CONSUMO','891-18961','Etiquetas autoadesivas e envelopes plásticos','Sim','','','01/10/25','01/06/26','Alta','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043',''),
	 (113,'STI','Pleitos','CUSTEIO-339030-STI',NULL,'9600,00','MATERIAL DE CONSUMO',' - ','Cabinas de votação para urnas eletrônicas','Sim','','','01/10/25','01/06/26','Alta','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043',''),
	 (114,'STI','Pleitos','CUSTEIO-33903019-STI',NULL,'2400,00','MATERIAL DE CONSUMO',' - ','Embalagem para Urna Eletrônica –  UE2020 e UE2022','Sim','','','01/10/25','01/06/26','Alta','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043',''),
	 (115,'STI','Pleitos','CUSTEIO-33903019-STI',NULL,'20000,00','MATERIAL DE CONSUMO',' - ','Embalagem permanente apropriada para transporte de baterias de urnas eletrônicas para as seções instaladas na zona rural e locais de difícil acesso','Sim','','','01/10/25','01/06/26','Alta','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043',''),
	 (116,'STI','Pleitos','CUSTEIO-3339030-STI',NULL,'10500,00','MATERIAL DE CONSUMO',' 8465-9831 ','Mochilas robustas (tipo cargueiro)','Sim','','','','01/10/25','Baixa','Garantia dos direitos fundamentais--- Enfrentamento à corrupção e à improbidade administrativa e aos ílicitos eleitorais---','','762043','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (117,'CIE','Pleitos','CUSTEIO-33904013-CIE',NULL,'2210000,00','LOCAÇÃO DE EQUIPAMENTO PARA TRANSMISSÃO VIA SATÉLITE',' 731-23019 ','A transmissão dos resultados dos Locais de Difícil Acesso - LDA é historicamente realizada por transmissão via satélite desde as eleições de 2000. Essa necessidade deve-se basicamente à total falta de outros meios de comunicação nestes locais. Alguns locais podem até ter algum meio de comunicação, mas o TRE-AC não tem gestão sobre os mesmos, e por conseguinte, qualquer garantia de que este meio de comunicação alternativo estará em funcionamento e se atenderá às especificações mínimas de funcionamento da VPN criada para recebimento dos resultados das eleições.','Sim','','','','01/08/26','Alta','Garantia dos direitos fundamentais--- Fortalecimento da Estratégia Nacional de TIC e proteção de dados.','','761010',''),
	 (118,'CIE','Pleitos','CUSTEIO-33904002-CIE',NULL,'20000,00','LOCAÇÃO DE TELAS PARA TRANSMISSÃO DO RESULTADO',' 881-14249 ','Locação de telas para transmissão do resultado para o 1º turno e 2º turno, se houver. Sendo R$ 10.000,00 para o 1º T e R$ 10.000,00 para o 2º T','Não','','','10/11/25','01/08/26','Média','Garantia dos direitos fundamentais/Fortalecimento da relação institucional com a sociedade','','761011',''),
	 (119,'SEMAP','Ordinário','INVESTIMENTO-44905242-SEMAP',NULL,'150000,00','Estação de trabalho, mesa linear, poltrona ergonômica, poltrona giratória, sofá','-',' Aquisição de bem permanente para atender às necessidades da secretaria e das zonas eleitorais do Tribunal ','Não','','','01/08/2025','07/01/2026','Alta','Promoção da sustentabilidade--- Aperfeiçoamento da gestão orçamentária e financeira---','-','761691',''),
	 (120,'SEMAP','Ordinário','INVESTIMENTO-44905230-SEMAP',NULL,'13000,00','Máquinas e equipamentos energéticos (nobreak)','-',' Aquisição de bem permanente para atender às necessidades da secretaria e das zonas eleitorais do Tribunal ','Não','','','01/08/2025','07/01/2026','Alta','Promoção da sustentabilidade--- Aperfeiçoamento da gestão orçamentária e financeira---','-','761691',''),
	 (121,'SEMAP','Ordinário','INVESTIMENTO-44905230-SEMAP',NULL,'60000,00','Eletrodomésticos, refrigerador, frigobar, liquidificador, micro-ondas, fogão, central de ar-condicionado, televisor','-',' Aquisição de bem permanente para atender às necessidades da secretaria e das zonas eleitorais do Tribunal ','Não','','','01/08/2025','07/01/2026','Alta','Promoção da sustentabilidade--- Aperfeiçoamento da gestão orçamentária e financeira---','-','761691',''),
	 (122,'STI','Ordinário','INVESTIMENTO-44905246-STI',NULL,'26800,00','SCANNER DE BASE PLANA E SCANNER PLANETÁRIO','7040-238','Utilizar dos equipamentos para o processo continuado de Digitalização da Massa Física e Gestão Documental do Tribunal Regional Eleitoral do Acre.','Sim','','','01/03/2025','01/08/2026','Média','Agilidade e produtividade na prestação jurisdicional/Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','759233',''),
	 (123,'EJE','Ordinário','INVESTIMENTO - EJE',NULL,'367750,71','Aquisição de móveis para montagem do Centro de Memória: bases paralelepípedo, expositores, totens em ACM, vitrines, painéis biombo, urna em madeira, puffs, cavaletes, suportes para banner, totens interativos e projetores interativos','','Montagem do Centro de Memória da Justiça Eleitoral, nos moldes previstos na Resolução CNJ 324/2020 e Resolução TRE 1.786/2023','Não','','','','07/01/2026','Alta','Garantia dos direitos fundamentais--- Fortalecimento da relação institucional com a sociedade---','0001561-45.2024.6.01.8000','758097',''),
	 (124,'STI','Ordinário','INVESTIMENTO-44904005-STI',NULL,'120000,00','SOFTWARE','','A justificativa da demanda foi inserida no evento 0742916, pela ASPLAN, a seguir reproduzida: "Os painéis de BI instalados pelo TRE-GO são estáticos, possuem limitações em relação à gestão de projetos estratégicos. O monitoramento dos projetos pelos gestores vai aprimorar a tomada de decisão".','Sim','','','01/11/25','01/03/26','Alta','Aperfeiçoamento da gestão administrativa e da governança judiciária---','-','751963',''),
	 (1,'STI','TSE','CUSTEIO',NULL,'275550,00','SOLUÇÃO DE GERENCIAMENTO DE ACESSOS PRIVILEGIADOS','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699',''),
	 (2,'STI','TSE','CUSTEIO',NULL,'1000000,00','SOLUÇÃO DE DATABASE FIREWALL','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699','');
INSERT INTO core.pca (item,unidade_requisitante,orcamento_ordinario_ou_pleitos,programa_unidade_responsavel,quantidade_a_ser_adquirida,valor_estimado,objeto_contratacao,codigo_catalogo_catmat_catser,justificativa_aquisicao,potencialmente_compartilhavel,vcto_contrato_em_vigor,data_maxima_prorrogacao_contrato,iniciar_providencias_contratacao,data_estimada_contratacao,prioridade,objetivo_estrategico_vinculado,processo_sei,evento_solicitacao,anotacoes) VALUES
	 (3,'STI','TSE','CUSTEIO',NULL,'119250,00','SOLUÇÃO DE SAST','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699',''),
	 (4,'STI','TSE','CUSTEIO',NULL,'300000,00','SOLUÇÃO DE GESTÃO DE RISCO R LGPD','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699',''),
	 (5,'STI','TSE','CUSTEIO',NULL,'150000,00','SOUÇÃO DE ACESSO REMOTO - ZERO TRUST','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699',''),
	 (6,'STI','TSE','CUSTEIO',NULL,'300000,00','SOLUÇÃO DE GERENCIAMENTO DE LOGS E EVENTOS - SIEM','','Proteger, de forma padronizada, a rede de dados da Justiça Eleitoral contra ataques e invasões por meio da aquisição de ferramentas e contratações soluções de segurança e defesa cibernética.','Sim','','','07/01/2026','01/06/2026','Alta','Fortalecimento da Estratégia Nacional de TIC e proteção de dados','-','751699','');
